#####################################################################################
# Program: cirq_qkd_best_approximate_clone.py
# Goal: This software implements the BB84 QKD protocol, simulating key agreement and 
#	eavesdropping attempts over both ideal and noisy quantum channels. The 
#	eavesdropper employs a phase-covariant qubit cloning strategy. The quantum 
#	simulation is repeated multiple times for each set of cloning parameters, 
#	with the objective of identifying the optimal parameters through statistical 
#	analysis.
# Date: 30th of May 2026  
# Ver: 1.1
# Author: Marco Mattiucci
#
# WARNING:
# It's strongly discouraged to install complex Python packages 
# like CirQ system-wide. Create an isolated environment:
# Create the directory:
# $ mkdir mycirq
# $ cd mycirq
# Install venv:
# $ sudo apt update
# $ sudo apt install python3-venv
# Verify owner:
# $ ls -ld .
# if owner is root:
# $ sudo chown -R $USER:$USER .
# Create the virtual environment (venv):
# $ python3 -m venv .venv
# Activate the venv:
# $ source .venv/bin/activate
# Upgrade pip and install CirQ:
# $ pip install --upgrade pip
# $ pip install cirq
#####################################################################################
# MIT License
#
# Copyright (c) 2026 Marco Mattiucci
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#####################################################################################






import cirq
import random
import hashlib
import math

def myhash(binary_list):
	return hashlib.sha256(str(binary_list).encode('utf-8')).hexdigest()

def get_sublist(L, n):
	if n == 0: return L
	r = math.floor((-1 + math.sqrt(1 + 8 * n)) / 2)
	T_r = (r * (r + 1)) // 2
	start = n - T_r
	end_offset = r - start
	end = len(L) - end_offset
	return L[start:end]
    



there_is_quantum_depolarization = False  	# Flag: Insert noise type 1 into the communication channel
depolarization_probability = 0.04		# Depolarizing noise probability in the communication channel
there_is_quantum_amplitude_decay = False 	# Flag: Insert noise type 2 into the communication channel
amplitude_decay_probability = 0.09		# Amplitude damping probability in the communication channel
nr_of_quantum_random_bits = 200			# Number of bits generated by the QRNG for the key

nr_of_attempts = 10		# Number of attempts for Teta2 and Teta3
nr_of_samples = 10		# For every attempt we perfom nr_of_samples quantum simulations
teta_1_double_list = []		# List of teta1 values
teta_2_double_list = []		# List of teta2 values
teta_3_double_list = []		# List of teta3 values
# Every element of the following list is the average QBER value for Bob on the i-th sample:
qber_bob_average_list = [0 for _ in range(nr_of_attempts)]	
# Every element of the following list is the average QBER value for Eve on the i-th sample
qber_eve_average_list = [0 for _ in range(nr_of_attempts)]	
# Every element of the following list is the percentage of intercepted bits by Eve on the i-th sample:
eve_percentage_of_intercepted_bit_average_list = [0 for _ in range(nr_of_attempts)] 

print()
print("Number of attempts for Teta2 and Teta3:",nr_of_attempts)
print("For every attemp we consider",nr_of_samples,"samples")
print("------------------------------")

# Main loop: evaluate different values of teta2:
for attempt in range(nr_of_attempts):
	
	print("Processing attempt nr.",attempt)
	# CALCULATE TETA2 and TETA3:
	# myfactor has to be between 0.25 and 0.5 of Pi for 2*teta2 and 2*teta3
	myfactor = 0.25*(1+(attempt+1)/(nr_of_attempts+1)) 
	teta_1_double = math.pi/2
	teta_2_double = math.pi*myfactor
	teta_3_double = teta_2_double
	teta_1_double_list.append(teta_1_double)
	teta_2_double_list.append(teta_2_double)
	teta_3_double_list.append(teta_3_double)

	# SIMULATION LOOP: 
	# For each teta2, compute the QBER for Bob and Eve, as well as the percentage of intercepted bits;
	# then evaluate the average QBERs and interception percentages across all samples.
	for sample in range(nr_of_samples):
	
		Q__channel = cirq.NamedQubit("Q__channel") # Main quantum communication channel
		CQ_channel = cirq.NamedQubit("CQ_channel") # Cloned quantum communication channel
		A__channel = cirq.NamedQubit("A__channel") # Ancilla quantum communication channel
		QRNGalice1 = cirq.NamedQubit("QRNGalice1") # Quantum channel 1 for QRNG1 (Alice random key)
		QRNGalice2 = cirq.NamedQubit("QRNGalice2") # Quantum channel 2 for QRNG2 (Alice random base)
		QRNGbob__1 = cirq.NamedQubit("QRNGbob__1") # Quantum channel 3 for QRNG3 (Bob random base)
	
		bob_errors = 0	# Nr of wrong bits received by Bob
		eve_errors = 0	# Nr of wrong bits received by Eve (eavesdropper)
		bob_key_bit_counter = 0	# Nr of bits received by Bod
		eve_intercepted_bit_counter = 0	# Nr of bits intercepted by Eve
		alice_random_bit_list = []	# List of bits issued by QRNG1 for Alice (includes the shared key)
		alice_key_bit_list = []		# List of bits selected by Alice for common base with Bob
		alice_random_base_list = []	# List of quantum random bases used by Alice
		alice_matching_bases_positions = []	# List of the bit positions where Alice's and Bob's bases match
		bob_key_bit_list = []		# List of bits selected by Bob where his basis matches Alice’s
		bob_random_base_list = []	# List of quantum random bases used by Bob
		bob_received_bit_list = []	# List of bits measured by Bod in the quantum channel
		bob_received_bad_bit_list = []	# List of bad bits selected by Bob where his basis matches Alice’s
		eve_key_bit_list = []		# List of bits selected by Eve for common base with Alice
		eve_pseudo_random_base_list = []	# List of pseudo-random bases used by Eve
		eve_intercepted_bit_list = []		# List of bits measured by Eve in the quantum channel
		eve_intercepted_bad_bit_list = []	# List of bad bits selected by Eve where Eve and Bod basis matches Alice’s
	
		#######################################################
		# Loop that emulates bit-by-bit quantum transmission; #
		# 1st communication phase:                            #
		#######################################################
		for i in range(nr_of_quantum_random_bits):
		
			# Create the quantum circuit:
			circuit = cirq.Circuit()
			
			####################
			# Alice Equipment: #
			####################
			
			# Insert Alice’s first Quantum Random Number Generator into the circuit:
			circuit.append(cirq.H(QRNGalice1))				# Insert a HADAMARD gate
			circuit.append(cirq.measure(QRNGalice1, key='QRNGalice1m'))	# Insert a MEASURE gate
			
			# Insert Alice’s second Quantum Random Number Generator into the circuit:
			circuit.append(cirq.H(QRNGalice2))				# Insert a HADAMARD gate
			circuit.append(cirq.measure(QRNGalice2, key='QRNGalice2m'))	# Insert a MEASURE gate
			
			# The first QRNG controls a NOT gate on the communication channel:
			circuit.append(cirq.X(Q__channel).with_classical_controls('QRNGalice1m'))
			
			# The second QRNG controls a HADAMARD gate on the communication channel:
			circuit.append(cirq.H(Q__channel).with_classical_controls('QRNGalice2m'))
	
			####################
			# Quantum channel: #
			####################
			
			# If required, insert noise type 1: depolarizing noise
			if there_is_quantum_depolarization:
				circuit.append(cirq.depolarize(p=depolarization_probability).on(Q__channel))
				
			# If required, insert noise type 2: amplitude damping
			if there_is_quantum_amplitude_decay:
				circuit.append(cirq.amplitude_damp(gamma=amplitude_decay_probability).on(Q__channel))
				
			#######################################################
			# Insert Eve’s equipment (eavesdropping/interception) #
			#######################################################
			# Cloning system:
			##############################
			
			circuit.append(cirq.Ry(rads=teta_1_double).on(CQ_channel))
			circuit.append(cirq.CNOT(CQ_channel,A__channel))
			
			circuit.append(cirq.Ry(rads=teta_2_double).on(A__channel))
			circuit.append(cirq.CNOT(A__channel,CQ_channel))
			
			circuit.append(cirq.Ry(rads=teta_3_double).on(CQ_channel))
			circuit.append(cirq.CNOT(Q__channel,CQ_channel))
			circuit.append(cirq.CNOT(Q__channel,A__channel))
			circuit.append(cirq.CNOT(CQ_channel,Q__channel))
			circuit.append(cirq.CNOT(A__channel,Q__channel))
			##############################
			# Insert a pseudorandom number generator for Eve in the cloned channel:
			eve_pseudo_random_base = random.choice([0, 1])			# Select a random base for Eve
			eve_pseudo_random_base_list.append(eve_pseudo_random_base)	# Store the random base in the list
			# If the random base is 1 apply HADAMARD - MEASURE:
			# The 1st Hadamard gate is for basis change:
			if eve_pseudo_random_base == 1:		
				circuit.append(cirq.H(CQ_channel))
			# In any case, apply a MEASURE gate to intercept the bit:
			circuit.append(cirq.measure(CQ_channel, key=f'eve_measure'))
				
			##################
			# Bob Equipment: #
			##################
			
			# Insert the third Quantum Random Number Generator for Bob into the circuit:
			circuit.append(cirq.H(QRNGbob__1))				# Insert a HADAMARD gate
			circuit.append(cirq.measure(QRNGbob__1, key='QRNGbob__1m'))	# Insert a MEASURE gate
			
			# The third QRNG controls a HADAMARD gate on the quantum communication channel:
			circuit.append(cirq.H(Q__channel).with_classical_controls('QRNGbob__1m'))	
			
			# Apply the MEASURE gate so that Bob can read the resulting bit:
			circuit.append(cirq.measure(Q__channel, key=f'bob_measure'))
	
			###############################
			# Quantum circuit simulation: #
			###############################
			
			simulatore = cirq.Simulator()		# Build the quantum simulator.
			risultati = simulatore.run(circuit)	# Run the quantum simulator.
			
			# Retrieve and store the measured bit values:
			alice_random_bit = int(risultati.measurements[f'QRNGalice1m'][0][0])	# Alice random bit on the communication channel.
			alice_random_bit_list.append(alice_random_bit)
			alice_random_base = int(risultati.measurements[f'QRNGalice2m'][0][0])	# Alice random base
			alice_random_base_list.append(alice_random_base)
			bob_random_base = int(risultati.measurements[f'QRNGbob__1m'][0][0])	# Bob random base
			bob_random_base_list.append(bob_random_base)
			bob_received_bit = int(risultati.measurements[f'bob_measure'][0][0])	# Bit received by Bob
			bob_received_bit_list.append(bob_received_bit)
			eve_intercepted_bit = int(risultati.measurements[f'eve_measure'][0][0])	# Eve intercepted bit
			eve_intercepted_bit_list.append(eve_intercepted_bit)
	
		####################################################
		# Loop that emulates bases comparison and sifting; #
		# 2nd communication phase:                         #
		####################################################
		for i in range(nr_of_quantum_random_bits):
			# Bod send bob_random_base_list[] to Alice;
			# Alice compares bob_random_base_list[] with alice_random_base_list[i] and
			# send back to Bob the positions of the matching bases:
			if alice_random_base_list[i] == bob_random_base_list[i]:
				alice_matching_bases_positions.append(i)		# Matching bases position
				alice_key_bit_list.append(alice_random_bit_list[i])	# Alice key bit list
				bob_key_bit_list.append(bob_received_bit_list[i])	# Bob key bit list
				bob_key_bit_counter += 1
				if alice_random_bit_list[i] != bob_received_bit_list[i]: 
					bob_errors += 1					# Bob errors
					bob_received_bad_bit_list.append(i)
				else:
					bob_received_bad_bit_list.append("_")
			else:
				alice_key_bit_list.append('_')
				bob_key_bit_list.append('_')
				
		#########################################################
		# Loop that emulates bases observation by Eve is there; #
		# 3rd communication phase (partial key extraction):     #
		#########################################################
		for i in range(nr_of_quantum_random_bits):
			# Eve uses the same bases of Alice and Bob where they matches:
			if alice_random_base_list[i] == bob_random_base_list[i] and alice_random_base_list[i] == eve_pseudo_random_base_list[i]:
				eve_intercepted_bit_counter += 1
				eve_key_bit_list.append(eve_intercepted_bit_list[i])		# Eve key bit list
				if alice_random_bit_list[i] != eve_intercepted_bit_list[i]: 
					eve_errors += 1						# Eve errors
					eve_intercepted_bad_bit_list.append(i)
				else:
					eve_intercepted_bad_bit_list.append("_")
			else:
				eve_key_bit_list.append('_')
		
		# Evaluate Bob's quantum bit error rate:
		qber_bob = bob_errors/bob_key_bit_counter	
		# Evaluate Eve's quantum bit error rate:	
		qber_eve = eve_errors/eve_intercepted_bit_counter
		# Evaluate average Bob's quantum bit error rate:
		qber_bob_average_list[attempt] += qber_bob/nr_of_samples	
		# Evaluate average Eve's quantum bit error rate:
		qber_eve_average_list[attempt] += qber_eve/nr_of_samples	
		# Evaluate average Eve's percentage of intercepted bits:
		eve_percentage_of_intercepted_bit_average_list[attempt] += eve_intercepted_bit_counter/bob_key_bit_counter/nr_of_samples
	
	###########
	# OUTPUT: #
	###########

	if qber_bob_average_list[attempt] > 0.11:	# The key agreement is rejected if the Average QBER exceeds 0.11
		print("\033[31m",end="")
		print("2*Teta1=",teta_1_double_list[attempt],"=Pi*0.5 - 2*Teta2=",teta_2_double_list[attempt],"=Pi*",myfactor)
		print("QBER_BOB(average)=",qber_bob_average_list[attempt],"QBER_EVE(average)=",qber_eve_average_list[attempt])
		print("Percentage of intercepted bit(s)(average)",eve_percentage_of_intercepted_bit_average_list[attempt])
		print("Alice and Bob discard the shared bits (Average QBER higher than 0.1).",end="")
		print("\033[0m")
	else:				# If the Average QBER remains below the threshold, the key agreement proceeds:
		print("\033[32m",end="")
		print("2*Teta1=",teta_1_double_list[attempt],"=Pi*0.5 - 2*Teta2=",teta_2_double_list[attempt],"=Pi*",myfactor)
		print("QBER_BOB(average)=",qber_bob_average_list[attempt],"QBER_EVE(average)=",qber_eve_average_list[attempt])
		print("Percentage of intercepted bit(s)(average)",eve_percentage_of_intercepted_bit_average_list[attempt])
		print("Alice and Bob retain the shared bits.",end="")
		print("\033[0m")

print("Done.")	

print()
print("QUANTUM CIRCUIT:")
print(circuit)

quit()
